modLoader = "javafml"
loaderVersion="${forge_loader_range}"
license="${mod_license}"
issueTrackerURL = "${mod_issue_url}"
showAsResourcePack = false

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_display_name}"
displayURL = "${mod_display_url}"
logoFile = "${mod_logo_file}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"