modLoader = "javafml"
loaderVersion = "[45,)"
license = "GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL = "https://github.com/HungTeen/HTLib/issues"
showAsResourcePack = false

[[mods]]
modId = "htlib"
version = "${file.jarVersion}"
displayName = "HungTeen's Lib"
updateJSONURL="https://hungteen.github.io/minecraft/mods/htlib.json"
displayURL = "https://space.bilibili.com/362855464"
logoFile = "logo.png"
credits = ""
authors = "HungTeen"
description = '''
Just a lib.
'''

[[dependencies.htlib]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.htlib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"