modLoader="javafml"
loaderVersion="[43,)"
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/HungTeen/HTLib/issues"

[[mods]]
modId="htlib"
version="${file.jarVersion}"
displayName="HungTeen's Lib"
displayURL="https://space.bilibili.com/362855464"
logoFile="examplemod.png"
credits=""
authors="HungTeen"
description='''
Just a lib.
'''

[[dependencies.htlib]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.htlib]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"